### ISSUE TITLE
thumb circle outside track (BUG)

### ISSUE THREAD

**Issue by abdoh476** [Shaninnik/PWSwitch#13]
I just put the switch in the screen configured it (details  in photo)
in code on data saved on user defaults I change it
if it false it open and became false
and if it true and open app the next photo happens
<img width="333" alt="Screen Shot 2019-11-27 at 10 57 13 AM" src="https://user-images.githubusercontent.com/9697328/69708660-ae4c5180-1104-11ea-869e-4c6dd61e06a7.png">

and this is a pic for the configuration 
<img width="263" alt="Screen Shot 2019-11-27 at 10 58 14 AM" src="https://user-images.githubusercontent.com/9697328/69708777-e0f64a00-1104-11ea-93c2-d314290e028d.png">

**Comment by Shaninnik** [comment]
I just tested doing `setOn` in `viewDidLoad` and everything works as expected. Can you post a simple reproduction case?

**Comment by abdoh476** [comment]
the problem I think was in constraint 
if it miss constraint this happens
