### ISSUE TITLE
Make switcher off by default or in life statement 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [Shaninnik/PWSwitch#3]
Thank you for your library. I just wanna know how to set the switch to off when the view appears ?

can I write an if statement like :

if name.text == "hello" {

pwSwitch.off

}

**Comment by Shaninnik** [comment]
Switch itself is Off by default. If you need to change state manually just call `setOn(on: Bool, animated :Bool)` to set it to On or Off state when needed.

**Comment by AbdulazizAlmohsen** [comment]
I tried PWSwitch.setOn(on: false, animated :true) but when I run the app the switch is in ON state
