### ISSUE TITLE
Track On Fill colour not working correctly. 

### ISSUE THREAD

**Issue by NSRover** [Shaninnik/PWSwitch#6]
I have created a PWSwitch like so: 

let customSwitch = PWSwitch(frame: CGRect(x: 0, y: 0, width: 36, height: 20))
customSwitch.borderWidth = 0
customSwitch.trackOnFillColor = .red
customSwitch.trackOffFillColor = .green

The red colour is only visible briefly during the transition and is replaced by a mustard yellow when the switch is On.

**Comment by NSRover** [comment]
I could achieve the desired result by also setting

customSwitch.trackOnBorderColor = .red

However, since the border width is set to 0 this should not have been necessary.

**Comment by Shaninnik** [comment]
Track/border color logic is a bit tricky because of on/off animation - border completely fills in entire track and acts like background color, so sometimes you need to experiment with values to achieve desired effect.

Also there is no `borderWidth` property for PWSwitch
